apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: test-logical-inventory-api
spec:
  backendType: gcpSecretsManager
  projectId: bcg-prj-lin-tt-invt-usc1-01
  controllerId: inventory
  data:
    - key: lin_mongodb_uri
      name: lin_mongodb_uri
      version: latest
    - key: lin_onera_apikey
      name: lin_onera_apikey
      version: latest
    - key: lin_onera_authorization
      name: lin_onera_authorization
      version: latest
